package view;

import crawler.SpiderLeg;
import dao.NewsDao;
import entity.News;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ManuelFrame extends javax.swing.JFrame {

    int newsId;

    public ManuelFrame() {
        initComponents();

        NewsDao newsDao = new NewsDao();

        try {
            newsDao.fillTable(tblNews);
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(ManuelFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNews = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtGdeItFactor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGlobalEventId = new javax.swing.JTextField();
        btnAra = new javax.swing.JButton();
        txtNewsDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtActors = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNewsId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSentiment = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTopic = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFakeTruthMatchNewsId = new javax.swing.JTextField();
        txtNewsTitle = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNewsDetail = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtDataSetId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblNews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NewsId", "DataSetId", "NewsDate", "Actors", "Sentiment", "Type", "Value", "FakeTruthMatchNewsId", "Topic", "Url", "NewsTitle", "NewsDetail", "GdeltFactor", "GlobalEventId"
            }
        ));
        tblNews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNewsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNews);
        tblNews.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabel9.setText("GdeItFactor");

        txtGdeItFactor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel11.setText("GlobalEventId");

        btnAra.setText("ARA");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtGdeItFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGlobalEventId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(959, 959, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGdeItFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtGlobalEventId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnAra)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtNewsDate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setText("Actors");

        jLabel1.setText("NewsId");

        txtNewsId.setEditable(false);

        jLabel2.setText("NewsDate");

        jLabel5.setText("Type");

        txtType.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setText("Value");

        jLabel7.setText("Sentiment");

        jLabel8.setText("Topic");

        txtTopic.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel10.setText("Url");

        jLabel12.setText("FakeTruthMatchNewsId");

        jLabel13.setText("NewsTitle");

        jLabel14.setText("NewsDetail");

        txtNewsDetail.setColumns(20);
        txtNewsDetail.setLineWrap(true);
        txtNewsDetail.setRows(7);
        txtNewsDetail.setAutoscrolls(false);
        jScrollPane2.setViewportView(txtNewsDetail);

        jLabel4.setText("DataSetId");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(txtNewsId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(txtDataSetId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNewsDate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtActors, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSentiment, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFakeTruthMatchNewsId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNewsTitle)))))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNewsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNewsDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtActors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSentiment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtFakeTruthMatchNewsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataSetId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtNewsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblNewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNewsMouseClicked
        newsId = (int) tblNews.getValueAt(tblNews.getSelectedRow(), 0);
        txtNewsId.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 0).toString());

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 1) != null) {
            txtDataSetId.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 1).toString());
        } else {
            txtDataSetId.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 2) != null) {
            txtNewsDate.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 2).toString());
        } else {
            txtNewsDate.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 3) != null) {
            txtActors.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 3).toString());
        } else {
            txtActors.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 4) != null) {
            txtSentiment.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 4).toString());
        } else {
            txtSentiment.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 5) != null) {
            txtType.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 5).toString());
        } else {
            txtType.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 6) != null) {
            txtValue.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 6).toString());
        } else {
            txtValue.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 7) != null) {
            txtFakeTruthMatchNewsId.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 7).toString());
        } else {
            txtFakeTruthMatchNewsId.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 8) != null) {
            txtTopic.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 8).toString());
        } else {
            txtTopic.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 9) != null) {
            txtUrl.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 9).toString());
        } else {
            txtUrl.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 10) != null) {
            txtNewsTitle.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 10).toString());
        } else {
            txtNewsTitle.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 11) != null) {
            txtNewsDetail.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 11).toString());
        } else {
            txtNewsDetail.setText("");
        }

        if (tblNews.getValueAt(tblNews.getSelectedRow(), 12) != null) {
            txtGdeItFactor.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 12).toString());
        } else {
            txtGdeItFactor.setText("");
        }
        if (tblNews.getValueAt(tblNews.getSelectedRow(), 13) != null) {
            txtGlobalEventId.setText(tblNews.getValueAt(tblNews.getSelectedRow(), 13).toString());
        } else {
            txtGlobalEventId.setText("");
        }


    }//GEN-LAST:event_tblNewsMouseClicked
    public void temizle() {
        txtNewsId.setText("");
        txtDataSetId.setText("");
        txtNewsDate.setText("");
        txtActors.setText("");
        txtSentiment.setText("");
        txtType.setText("");
        txtValue.setText("");
        txtFakeTruthMatchNewsId.setText("");
        txtTopic.setText("");
        txtUrl.setText("");
        txtNewsTitle.setText("");
        txtNewsDetail.setText("");
        txtGdeItFactor.setText("");
        txtGlobalEventId.setText("");
    }
    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
        
        SpiderLeg spiderLeg = new SpiderLeg();
        
        String newsDetail = new String();
        
        try {
            newsDetail = spiderLeg.getValue(txtUrl.getText().toString(), txtActors.getText().toString());
        } catch (IOException ex) {
            Logger.getLogger(ManuelFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtNewsDetail.setText(newsDetail);
    }//GEN-LAST:event_btnAraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManuelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblNews;
    private javax.swing.JTextField txtActors;
    private javax.swing.JTextField txtDataSetId;
    private javax.swing.JTextField txtFakeTruthMatchNewsId;
    private javax.swing.JTextField txtGdeItFactor;
    private javax.swing.JTextField txtGlobalEventId;
    private javax.swing.JTextField txtNewsDate;
    private javax.swing.JTextArea txtNewsDetail;
    private javax.swing.JTextField txtNewsId;
    private javax.swing.JTextField txtNewsTitle;
    private javax.swing.JTextField txtSentiment;
    private javax.swing.JTextField txtTopic;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
